name: Process Onchain Data and Create Issue

on:
  repository_dispatch:
    types: [onchain-event]

  workflow_dispatch:
    inputs:
      body:
        description: 'body'
        required: false
        default: 'Body, expecting json'

# https://api.github.com/repos/shayanb/actions/dispatches


jobs:
  process_and_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        pip install requests

    - name: Fetch webhook data and process
      env:
        PAYLOAD: ${{ github.event.body }}
      id: exec_script
      run: |
        python ./scripts/decode_to_github_issues.py "${{ github.event.client_payload.body }}" > output.md


    - name: Print the Markdown content
      run: echo "$MARKDOWN"

    - name: Create GitHub Issue from Markdown File
      uses: peter-evans/create-issue-from-file@v5
      env:
        MARKDOWN: ${{ env.MARKDOWN }}
      with:
        token: ${{ secrets.TOKEN }}
        title: "Onchain Update on $(date +'%Y-%m-%d %H:%M:%S')"
        labels: onchain update, automated
        content-filepath: output.md

